repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.12
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  # -  repo: https://github.com/lorenzwalthert/precommit
  #    rev: v0.4.3.9021
  #    hooks:
  #     - id: lintr
  #       args: [--warn_only]
  #       verbose: true
  #     - id: style-files
  #       args: [--scope=tokens, --strict=true, --reindention=specify_reindention('#'), --indent_by=4, --start_comments_with_one_space=true]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--skip, "*.bib,*.tex,*.ipynb", --ignore-words-list, "nd,ser,ba,fpr"]
        exclude: '\.(tsv|csv|json|txt|lock)$'

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.21.2
      hooks:
      -   id: pyupgrade
          args: [--py313-plus]
